### ISSUE TITLE
 Also link to PDF

### ISSUE THREAD

**Issue by lassepe** [arXiv/html_feedback#465] opened 2024-02-14 11:27 UTC
### Description

I really like the new HTML feature. However, for offline use, PDF is still a great format. In the current layout of the html version, there is no link to download the PDF. When google links to the HTML version, the PDF can be surprisingly difficult to find: the "fastest" path to it currently is by editing the URL, replacing "html" with "pdf" . Accessibility of the PDF could be improved by explicitly offering the PDF for download via a button on the HTML page, too.

### (Required) What is this issue most closely related to? Select one.

Formula

### Internal issue ID

e5d73a51-4bc1-465a-8a08-28e3b4cca3b3

### Paper URL

https://arxiv.org/html/2312.02430v1

### Browser

Chrome/121.0.0.0

### Device Type

Desktop

**Comment by chrisjcameron** [comment] 2024-02-15 18:54
Duplicate of #226

**Closed** 2024-02-16 10:46 UTC
Labels: feature-request
